@startuml

state GuestUser {
    [*] --> Unregistered : Enter NewsSystem

    state choice_state <<choice>>
    Unregistered --> choice_state : LogIn
    choice_state --> LoggingIn : registered
    choice_state --> Registration : not registered

    state join_state <<choice>>
    LoggingIn --> join_state
    Registration --> join_state
    join_state --> Registered : Enter NewsSystem as RegistedUser

    Registered --> Unregistered: LogOut
    
    Unregistered --> [*] : Leave NewsSystem
    Registered --> [*]  : Leave NewsSystem

}

state Unregistered  : ViewNews
state Unregistered  : ShareNews
state Unregistered  : SearchNews


state Registration : ShowRegistryForm
state Registration : AddingUserToDB

state LoggingIn : ShowLogInForm
state LoggingIn : CheckingForUserInDB

state Registered : ManageProfile
state Registered : ViewNews
state Registered : ShareNews
state Registered : SearchNews

@enduml
