@startuml

state GuestUser {
    [*] --> Unregistered : Enter NewsSystem

    state fork_state <<fork>>
    Unregistered --> fork_state : LogIn
    fork_state --> LoggingIn : <<if registered>>
    fork_state --> Registration : <<if not registered>>

    state join_state <<join>>
    LoggingIn --> join_state
    Registration --> join_state
    join_state --> Registered : Enter NewsSystem as RegistedUser

    Registered --> Unregistered: LogOut
    
    Unregistered --> [*] : Leave NewsSystem
    Registered --> [*]  : Leave NewsSystem

}

state Unregistered  : ViewNews
state Unregistered  : ShareNews
state Unregistered  : SearchNews


state Registration : ShowRegistryForm
state Registration : AddingUserToDB

state LoggingIn : ShowLogInForm
state LoggingIn : CheckingForUserInDB

state Registered : ManageProfile
state Registered : ViewNews
state Registered : ShareNews
state Registered : SearchNews

@enduml
